#pragma once
#ifdef ANDROID
#include <AppPlatform.hpp>
#include <jni.h>

struct ANativeActivity;
struct AppPlatform_android : AppPlatform{
	jobject mainActivityRef;
	jmethodID _jniSaveScreenshot;
	jmethodID _jniPostScreenshotToFacebook;
	jmethodID _jniGetImageData;
	jmethodID _jniGetFileDataBytes;
	jmethodID _jniPlaySound_NOTFOUND;
	jmethodID _jniDisplayDialog;
	jmethodID _jniTick;
	jmethodID _jniQuit;
	jmethodID _jniInitiateUserInput;
	jmethodID _jniGetUserInputStatus;
	jmethodID _jniGetUserInputString;
	jmethodID field_50;
	jmethodID _jniCheckLicense;
	jmethodID _jniHasBuyButtonWhenInvalidLicense;
	jmethodID _jniBuyGame;
	int field_60;
	int field_64;
	jmethodID _jniGetPixelsPerMillimeter;
	jmethodID _jniVibrate;
	jmethodID _jniSupportsNonTouchscreen;
	jmethodID _jniSetIsPowerVR;
	jmethodID _jniIsNetworkEnabled;
	jmethodID _jniOpenLoginWindow;
	int field_80;
	int field_84;
	int field_88;
	int field_8C;
	jmethodID _jniWebRequest;
	jmethodID _jniGetWebRequestStatus;
	jmethodID _jniGetWebRequestContent;
	jmethodID _jniAbortWebRequest;
	jmethodID _jniGetPlatformStringVar;
	jclass windowReference;
	jclass contextReference;
	jfieldID _jniS_INPUT_METHOD_SERVICE;
	jclass inputMethodHandlerReference;
	jmethodID _jniGetSystemService;
	jmethodID _jniGetWindow;
	jmethodID _jniGetDecorView;
	jmethodID _jniShowSoftInput;
	jclass viewReference;
	jmethodID _jniGetWindowToken;
	jmethodID _jniHideSoftInputFromWindow;
	jmethodID _jniGetKeyFromCode;
	jmethodID _jniShowKeyboard;
	jmethodID _jniHideKeyboard;
	jmethodID _jniUpdateTextboxText;
	jmethodID _jniGetAccessToken;
	jmethodID _jniGetClientID;
	jmethodID _jniGetProfileID;
	jmethodID _jniGetProfileName;
	jmethodID _jniSetLoginInformation;
	jmethodID _jniClearLoginInformation;
	jmethodID _jniStatsTrackEvent;
	jmethodID _jniStatsUpdateUserData;
	int screenWidth;
	int screenHeight;
	bool field_108;
	//align
	ANativeActivity* field_10C;
	bool initialized;
	JavaVM* jvm;
	jclass mainActivityReference;

	AppPlatform_android();
	void init(JavaVM*);
	void convertOpenGlToAndroidPixels(int, int, unsigned int*);

	virtual ~AppPlatform_android();
	virtual void saveScreenshot(std::string const&, int, int);
	virtual std::string getImagePath(const std::string&, bool_t);
	virtual void loadPNG(ImageData&, const std::string&, bool_t);
	virtual void loadTGA(ImageData&, const std::string&, bool_t);
	virtual void playSound(const std::string&, float, float);
	virtual void showDialog(int32_t);
	virtual void createUserInput(void);
	virtual int32_t getUserInputStatus(void);
	virtual std::vector<std::string> getUserInput(void);
	virtual std::string getDateString(int32_t);
	virtual int32_t checkLicense(void);
	virtual bool_t hasBuyButtonWhenInvalidLicense(void);
	virtual void uploadPlatformDependentData(int32_t, void*);
	virtual AssetFile readAssetFile(const std::string&);
	virtual int32_t getScreenWidth(void);
	virtual int32_t getScreenHeight(void);
	virtual float getPixelsPerMillimeter(void);
	virtual bool_t isNetworkEnabled(bool_t);
	virtual void openLoginWindow(void);
	virtual bool_t isPowerVR(void);
	virtual int32_t getKeyFromKeyCode(int32_t, int32_t, int32_t);
	virtual void buyGame(void);
	virtual void finish(void);
	virtual bool supportsTouchscreen(void);
	virtual bool_t supportsVibration(void);
	virtual void vibrate(int32_t);
	virtual std::string getPlatformStringVar(int32_t);
	virtual void showKeyboard(std::string*, int32_t, bool_t);
	virtual void hideKeyboard(void);
	virtual void updateTextBoxText(const std::string&);
	virtual LoginInformation getLoginInformation(void);
	virtual void setLoginInformation(const LoginInformation&);
	virtual void clearSessionIDAndRefreshToken(void);
	virtual void statsTrackData(const std::string&, const std::string&);
	virtual void updateStatsUserData(const std::string&, const std::string&);
	virtual void initWithActivity(ANativeActivity*);
	virtual void webRequest(int, long long, const std::string&, const std::string&, const std::string&, const std::string&);
	virtual int getWebRequestStatus(int);
	virtual std::string getWebRequestContent(int);
	virtual int abortWebRequest(int);
};
#endif
