# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: 测试

on:
  push:
  workflow_dispatch:    
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: install pkgs
      run: |
        sudo apt update
        sudo apt install -y libsdl1.2-dev libopenal-dev libgl1-mesa-dev zlib1g-dev libcurl4-openssl-dev
    - name: do cmake stuff 
      run: |
        mkdir build/
        cd build/
        cmake .. -DDYNAMICSOUNDS=ON
        make -j8
    - name: upload stuff
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: 
          build/minecraftpe/build/minecraftpe08decomp

  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install pkgs
      run: |
        sudo apt update
        sudo apt install -y gcc-mingw-w64 libz-mingw-w64-dev g++-mingw-w64 wget unzip libsdl1.2debian libsdl1.2-dev libopenal-dev libgl1-mesa-dev zlib1g-dev libcurl4-openssl-dev unzip
    
    - name: do cmake stuff 
      run: |
        mkdir build/
        cd build/
        echo "- Downloading SDL and CURL -"
        wget https://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz
        wget https://www.libsdl.org/release/SDL-1.2.15-win32-x64.zip
        wget https://curl.se/download/curl-8.20.0.tar.gz
        
        echo "- Unzipping libs -"
        tar -xf SDL-devel-1.2.15-mingw32.tar.gz
        unzip -u SDL-1.2.15-win32-x64.zip
        tar -xf curl-8.20.0.tar.gz

        cp SDL-1.2.15/include/SDL -r ../minecraftpe/headers/ 
        
        echo "- Building curl -"
        cd curl-8.20.0/
        ./configure --host=x86_64-w64-mingw32 --prefix=$PWD/build-win64 --enable-static --enable-shared --without-libpsl --with-schannel --disable-docs
        make -j8
        make install
        cd ..
        
        echo "start building"
        export CURDIR=$DIRSTACK
        cmake .. -DDYNAMICSOUNDS=ON -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS} -static" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCURL_INCLUDE_DIR="$CURDIR/curl-8.20.0/build-win64/include/" -DCURL_LIBRARY="$CURDIR/curl-8.20.0/build-win64/bin/libcurl-4.dll" -DSDL_LIBRARY="$CURDIR/SDL.dll" -DSDL_INCLUDE_DIR="$CURDIR/SDL-1.2.15/include/" -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32/
        make -j8

        cp minecraftpe/build/minecraftpe08decomp.exe .
        cp curl-8.20.0/build-win64/bin/libcurl-4.dll .
        
    - name: upload stuff
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: |
          build/minecraftpe08decomp.exe
          build/SDL.dll
          build/libcurl-4.dll
